#!/bin/bash -e

# $MYSQL_DATABASE用のユーザーの作成
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE USER '$MYSQL_APP_USER'@'%' IDENTIFIED BY '$MYSQL_APP_PASSWORD';"

# $MYSQL_DATABASE用の権限の作成
mysql -u root -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL ON $MYSQL_DATABASE.* TO '$MYSQL_APP_USER'@'%' WITH GRANT OPTION;"

